# Site settings
title: Your Name
email: your.email@example.com
description: Personal website of Your Name, Researcher/Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
github_username: yourusername
twitter_username: yourhandle
linkedin_username: yourprofile
google_scholar: yourid

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE
  - backups 